name: "CD - Dev ツ"

on:
  push:
    branches:
      - dev

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and Push to GitHub Packages
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/ingsis-group10-2024/snippet-permission-dev:latest

  deploy:
    name: Permission dev deployment
    runs-on: ubuntu-latest
    needs: build-and-publish

    steps:
      - name: Update and Restart Permission Infrastructure
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_URL }}
          username: "mcchicken"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd snippet-infra 
            sudo su
            docker container stop snippet-permission  
            docker container rm snippet-permission  
            docker-compose -f docker-compose.prod.yml pull permission  
            docker-compose -f docker-compose.prod.yml up -d permission  
            docker image prune -f