name: "CD Pipeline for Snippet-Permission ツ"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      # Forma de versionar la imagen usando un hash del commit
      - name: Create Short SHA
        uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 8

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/snippet-permission:latest
          # ${{secrets.DOCKER_USERNAME}}/snippet-permission:${{ steps.short-sha.outputs.sha }}
          # para usar la como tag de la imagen el sha del commit